name: Build and test

on: [workflow_dispatch]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v4.4
          target: esp32
          path: '.'
      - name: Install the Wokwi CLI
        run: |
          wget -O /usr/local/bin/wokwi-cli https://github.com/wokwi/wokwi-cli/releases/latest/download/wokwi-cli-linuxstatic-x64
          chmod +x /usr/local/bin/wokwi-cli
      - name: Simulate and test the project
        run: wokwi-cli --expect-text "any webserver online" --timeout 10000
        env:
          WOKWI_CLI_TOKEN: ${{ secrets.WOKWI_CLI_TOKEN }}
